global:
  storageProvider:
    provider: "apiserver"
    apiserver:
      context: ""
      namespace: "radius-system"
  queueProvider:
      provider: "apiserver"
      apiserver:
        context: ""
        namespace: "radius-system" 

  
