global:
  storageProvider:
    provider: "apiserver"
    apiserver:
      context: ""
      namespace: "radius-system"
  queueProvider:
    provider: "apiserver"
    name: "radius"
    apiserver:
      context: ""
      namespace: "radius-system"
